# Generated by Django 3.2.6 on 2021-10-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Banka adı')),
                ('iban_no', models.CharField(max_length=26, verbose_name='Iban No')),
                ('hesap_no', models.CharField(blank=True, max_length=12, null=True, verbose_name='Hesap No')),
                ('branch_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Şube adı')),
                ('branch_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='Şube No')),
                ('status', models.BooleanField(default='True', verbose_name='Banka Durumu')),
            ],
            options={
                'verbose_name': 'Bankalar',
                'verbose_name_plural': 'Bankalar',
            },
        ),
    ]
