# Generated by Django 3.2.6 on 2021-10-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20211024_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='bank_name',
            field=models.CharField(default=2, max_length=100, verbose_name='Banka adı'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Banka adı'),
        ),
    ]
