# Generated by Django 3.2.6 on 2021-10-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_auto_20211024_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Alıcı Adı'),
        ),
    ]
