# Generated by Django 3.2.6 on 2021-10-24 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_alter_bank_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ödeme Tarihi'),
        ),
    ]
