# Generated by Django 3.2.6 on 2021-10-26 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0008_auto_20211026_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=100, verbose_name='İşlem Açıklama')),
                ('status', models.BooleanField(default='False', verbose_name='Açıklama Durumu')),
            ],
            options={
                'verbose_name': 'Ödeme Açıklama',
                'verbose_name_plural': 'Ödeme Açıklama',
            },
        ),
        migrations.CreateModel(
            name='Transfer_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=100, verbose_name='İşlem Açıklama')),
                ('status', models.BooleanField(default='False', verbose_name='Açıklama Durumu')),
            ],
            options={
                'verbose_name': 'Havale Açıklama',
                'verbose_name_plural': 'Havale Açıklama',
            },
        ),
        migrations.RemoveField(
            model_name='payment',
            name='check_status',
        ),
        migrations.AddField(
            model_name='payment',
            name='commentid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.payment_comment', verbose_name='İşlem Açıklama'),
        ),
        migrations.AddField(
            model_name='payment_transfer',
            name='commentid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.transfer_comment', verbose_name='İşlem Açıklama'),
        ),
    ]
