# Generated by Django 3.2.6 on 2021-10-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0009_auto_20211026_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_comment',
            name='status',
            field=models.BooleanField(default='True', verbose_name='Açıklama Durumu'),
        ),
        migrations.AlterField(
            model_name='transfer_comment',
            name='status',
            field=models.BooleanField(default='True', verbose_name='Açıklama Durumu'),
        ),
    ]
