# Generated by Django 3.2.6 on 2021-10-26 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0010_auto_20211026_1549'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment_comment',
            options={'verbose_name': 'Ödeme İşlem', 'verbose_name_plural': 'Ödeme İşlem'},
        ),
        migrations.AlterModelOptions(
            name='transfer_comment',
            options={'verbose_name': 'Havale İşlem', 'verbose_name_plural': 'Havale İşlem'},
        ),
        migrations.AlterField(
            model_name='payment',
            name='commentid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bank.payment_comment', verbose_name='İşlem Açıklama'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment_transfer',
            name='commentid',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='bank.transfer_comment', verbose_name='İşlem Açıklama'),
            preserve_default=False,
        ),
    ]
