# Generated by Django 3.2.6 on 2021-10-10 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0003_alter_members_classes_coment_limit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Raffle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, serialize=False, verbose_name='Başlık')),
                ('post_url', models.URLField(verbose_name='Post url')),
                ('username', models.CharField(max_length=100, verbose_name='Username')),
                ('count_a_user', models.BooleanField(verbose_name='Kullanıcı bir kere sayılsın')),
                ('tag', models.IntegerField(verbose_name='Etiket Sayısı')),
                ('text_list', models.TextField(null=True, verbose_name='Yorumda olması gereken yazılar')),
                ('follow_list', models.TextField(null=True, verbose_name='Takip etmesi gerekenler')),
                ('main_user_list', models.TextField(verbose_name='Tüm yapılan yorumlar')),
                ('winner', models.IntegerField(verbose_name='Kazanan Sayısı')),
                ('backup_winner', models.IntegerField(verbose_name='Yedek Sayısı')),
                ('animate_time', models.IntegerField(verbose_name='Animasyon süresi')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True, verbose_name='Durum')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.members_classes', verbose_name='Member_id')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User_id')),
            ],
        ),
        migrations.CreateModel(
            name='Raffle_Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner_list', models.TextField(verbose_name='Kazanan listesi')),
                ('backup_list', models.TextField(verbose_name='Yedek listesi')),
                ('valid_user_list', models.TextField(verbose_name='Filtrelenmiş kullanıcı listesi')),
                ('status', models.BooleanField(default=True, verbose_name='Durum')),
                ('raffle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raffle.raffle', verbose_name='Çekiliş Numarası')),
            ],
        ),
    ]
