# Generated by Django 3.2.6 on 2021-09-28 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member_offers',
            name='n_times',
            field=models.IntegerField(verbose_name='Adet'),
        ),
        migrations.AlterField(
            model_name='member_offers',
            name='price',
            field=models.IntegerField(verbose_name='Fiyat'),
        ),
        migrations.AlterField(
            model_name='user_member_class',
            name='n_times',
            field=models.IntegerField(verbose_name='Kalan Hakkı'),
        ),
    ]
