# Generated by Django 3.2.6 on 2021-09-28 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20210929_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members_classes',
            name='coment_limit',
            field=models.IntegerField(verbose_name='Çekilecek Yorum Limiti'),
        ),
    ]
