# Generated by Django 3.2.6 on 2021-10-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_members_classes_coment_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member_offers',
            name='price',
            field=models.FloatField(verbose_name='Fiyat'),
        ),
    ]
